<!DOCTYPE html>
<html>
<head>
	<title>Async/Await</title>
	<link rel="stylesheet" type="text/css" href="../../Assets/bulma.css">
	<link rel="stylesheet" type="text/css" href="../../Assets/Style.css">
	<script type="text/javascript" src="../../Assets/prism.min.js"></script>
	<script type="text/javascript" src="../../Assets/jquery.min.js"></script>
  <link rel="stylesheet" href="../../Assets/prism-dark.css">
</head>
<body class="Body">
<div class="Content Card">







<h1>Async/Await</h1>
<p>There’s a special syntax to work with promises in a more comfortable fashion, called “async/await”. It’s surprisingly easy to understand and use. Let’s start with the <code>async</code> keyword. It can be placed before a function, like this:</p>
<pre>
async function f() {
  return 1;
}
</pre>
<p>The word “async” before a function means one simple thing: a function always returns a promise. Even If a function actually returns a non-promise value, prepending the function definition with the “async” keyword directs Javascript to automatically wrap that value in a resolved promise. For instance, the code above returns a resolved promise with the result of <code>1</code>, let’s test it:</p>
<pre>
async function f() {
  return 1;
}

f().then(alert); // 1
</pre>
<p>…We could explicitly return a promise, that would be the same:</p>
<pre>
async function f() {
  return Promise.resolve(1);
}

f().then(alert); // 1
</pre>
<p>So, <code>async</code> ensures that the function returns a promise, and wraps non-promises in it. Simple enough, right? But not only that. There’s another keyword, <code>await</code>, that works only inside <code>async</code> functions, and it’s pretty cool.</p>
<pre>
// works only inside async functions
let value = await promise;
</pre>
<p>The keyword <code>await</code> makes JavaScript wait until that promise settles and returns its result. Here’s an example with a promise that resolves in <code>1</code> second:</p>
<pre>
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });

  let result = await promise; // wait till the promise resolves (*)

  alert(result); // "done!"
}

f();
</pre>
<p>The function execution “pauses” at the line <code>(*)</code> and resumes when the promise settles, with result becoming its result. So the code above shows “done!” in one second.</p>
<p>Let’s emphasize: <code>await</code> literally makes JavaScript wait until the promise settles, and then go on with the result. That doesn’t cost any CPU resources, because the engine can do other jobs meanwhile: execute other scripts, handle events etc.</p>
<p>It’s just a more elegant syntax of getting the promise result than <code>promise.then</code>, easier to read and write.</p>
<h3>Can’t use await in regular functions</h3>
<p>If we try to use <code>await</code> in non-async function, that would be a syntax error:</p>
<pre>
function f() {
  let promise = Promise.resolve(1);
  let result = await promise; // Syntax error
}
</pre>
<p>We will get this error if we do not put <code>async</code> before a function. As said, <code>await</code> only works inside an <code>async</code> function.</p>
<h3>await accepts thenables</h3>
<p>Like <code>promise.then</code>, <code>await</code> allows to use thenable objects (those with a callable then method). Again, the idea is that a 3rd-party object may not be a promise, but promise-compatible: if it supports <code>.then</code>, that’s enough to use with <code>await</code>.</p>
<p>For instance, here <code>await</code> accepts <code>new Thenable(1)</code>:</p>
<pre>
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve); // function() { native code }
    // resolve with this.num*2 after 1000ms
    setTimeout(() => resolve(this.num * 2), 1000); // (*)
  }
};

async function f() {
  // waits for 1 second, then result becomes 2
  let result = await new Thenable(1);
  alert(result);
}

f();
</pre>
<p>If <code>await</code> gets a non-promise object with <code>.then</code>, it calls that method providing native functions resolve, reject as arguments. Then <code>await</code> waits until one of them is called (in the example above it happens in the line <code>(*)</code>) and then proceeds with the result.</p>











<h1>Async methods</h1>
<p>A class method can also be async, just put async before it.</p>
<pre>
class Waiter {
  async wait() {
    return await Promise.resolve(1);
  }
}

new Waiter()
  .wait()
  .then(alert); // 1
</pre>
<p>The meaning is the same: it ensures that the returned value is a promise and enables <code>await</code>.</p>









<h1>Error handling</h1>
<p>If a promise resolves normally, then await promise returns the result. But in case of a rejection, it throws the error, just as if there were a throw statement at that line.</p>
<p>The code:</p>
<pre>
async function f() {
  await Promise.reject(new Error("Whoops!"));
}
</pre>
<p>…Is the same as this:</p>
<pre>
async function f() {
  throw new Error("Whoops!");
}
</pre>
<p>In real situations, the promise may take some time before it rejects. So <code>await</code> will wait, and then throw an error. We can catch that error using <code>try..catch</code>, the same way as a regular throw:</p>
<pre>
async function f() {
  try {
    let response = await fetch('http://no-such-url');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
</pre>
<p>In case of an error, the control jumps to the <code>catch</code> block. We can also wrap multiple lines:</p>
<pre>
async function f() {

  try {
    let response = await fetch('/no-user-here');
    let user = await response.json();
  } catch(err) {
    // catches errors both in fetch and response.json
    alert(err);
  }
}

f();
</pre>
<p>If we don’t have <code>try..catch</code>, then the promise generated by the call of the async function <code>f()</code> becomes rejected. We can append <code>.catch</code> to handle it:</p>
<pre>
async function f() {
  let response = await fetch('http://no-such-url');
}

// f() becomes a rejected promise
f().catch(alert); // TypeError: failed to fetch // (*)
</pre>








<h1>async/await and promise.then/catch</h1>
<p>When we use <code>async</code>/<code>await</code>, we rarely need <code>.then</code>, because <code>await</code> handles the waiting for us. And we can use a regular <code>try..catch</code> instead of <code>.catch</code>. That’s usually (not always) more convenient.</p>
<p>But at the top level of the code, when we’re outside of any <code>async</code> function, we’re syntactically unable to use <code>await</code>, so it’s a normal practice to add <code>.then</code>/<code>catch</code> to handle the final result or falling-through errors.</p>
<h3>async/await works well with Promise.all</h3>
<p>When we need to wait for multiple promises, we can wrap them in <code>Promise.all</code> and then <code>await</code>:</p>
<pre>
// wait for the array of results
let results = await Promise.all([
  fetch(url1),
  fetch(url2),
  ...
]);
</pre>
















</div>
</body>
</html>